config/routes.rb
Arcman::Application.routes.draw do

  scope "api" do
    resources :positions
    resources :documents
  end

  match "/images/uploads/*path" => "gridfs#serve"

  root :to => 'main#index'

end

app/models/document.rb
class Document
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :date, type: String
  field :file_doc, type: String
  mount_uploader :file_doc, FileDocUploader
  has_and_belongs_to_many :dossiers
  has_and_belongs_to_many :tags   
end

app/models/dossier.rb
class Dossier
  include Mongoid::Document
  field :name, type: String
  has_and_belongs_to_many :documents
  belongs_to :position
end

app/models/emplacement.rb
class Emplacement < Position
  belongs_to :salle, :foreign_key=>:emplacement_id, :polymorphic=> true
end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :description, :emplacement
  belongs_to :emplacement, :polymorphic=> true
  has_and_belongs_to_many :tags
end

app/models/salle.rb
class Salle < Position
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :nom
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  respond_to :json

  def index
    respond_with Document.all
  end

  def show
    respond_with Document.find(params[:id])
  end

  def create
    @doc = Document.new
    @doc.title = params['Filename']
    @doc.file_doc = params['Filedata']       
#    respond_with Document.create(params[:document])
    respond_to do |format|
      if @doc.save!
        format.html { render text: "doc  was successfully created." }
        format.json { render json: @doc, status: :created, location: @doc }
      else
        format.html { render text: "doc  was not successfully created." }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_with Document.update(params[:id],params[:document])
  end

  def destroy
    respond_with Document.find(params[:id]).destroy
  end
end

app/controllers/gridfs_controller.rb
require 'mongo'

class GridfsController < ActionController::Metal
  def serve
    gridfs_path = env["PATH_INFO"].gsub("/images/", "")
    begin
      gridfs_file = Mongo::GridFileSystem.new(Mongoid.database).open(gridfs_path, 'r')
      self.response_body = gridfs_file.read
      self.content_type = gridfs_file.content_type
    rescue
      self.status = :file_not_found
      self.content_type = 'text/plain'
      self.response_body = ''
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/documents/_form.html.erb
<%= form_for @document, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :descriptif, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descriptif, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :position_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :position_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :position_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                documents_path, :class => 'btn' %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<%- model_class = @document.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/documents/index.html.erb
<%- model_class = Document.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:descriptif) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:position_type) %></th>
      <th><%= model_class.human_attribute_name(:position_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= link_to document.id, document_path(document) %></td>
        <td><%= document.descriptif %></td>
        <td><%= document.date %></td>
        <td><%= document.url %></td>
        <td><%= document.position_type %></td>
        <td><%= document.position_id %></td>
        <td><%=l document.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_document_path(document), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      document_path(document),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_document_path,
            :class => 'btn btn-primary' %>

app/views/documents/new.html.erb
<%- model_class = @document.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/documents/show.html.erb
<%- model_class = @document.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:descriptif) %>:</strong></dt>
  <dd><%= @document.descriptif %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @document.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @document.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position_type) %>:</strong></dt>
  <dd><%= @document.position_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position_id) %>:</strong></dt>
  <dd><%= @document.position_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              documents_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_document_path(@document), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              document_path(@document),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Arcman" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Les documents</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Archiver", "/#upload"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Archiver", "/#upload"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/main/index.html.erb
<div id="container">Loading....</div>

app/views/positions/_form.html.erb
<%= form_for @position, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :emplacement_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :emplacement_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :emplacement_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :emplacement_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                positions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<%- model_class = @position.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/positions/index.html.erb
<%- model_class = Position.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:emplacement_type) %></th>
      <th><%= model_class.human_attribute_name(:emplacement_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= link_to position.id, position_path(position) %></td>
        <td><%= position.description %></td>
        <td><%= position.type %></td>
        <td><%= position.emplacement_type %></td>
        <td><%= position.emplacement_id %></td>
        <td><%=l position.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_position_path(position), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      position_path(position),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_position_path,
            :class => 'btn btn-primary' %>

app/views/positions/new.html.erb
<%- model_class = @position.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/positions/show.html.erb
<%- model_class = @position.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @position.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @position.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emplacement_type) %>:</strong></dt>
  <dd><%= @position.emplacement_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emplacement_id) %>:</strong></dt>
  <dd><%= @position.emplacement_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              positions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_position_path(@position), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              position_path(@position),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>